### ISSUE TITLE
installation checklist

### ISSUE THREAD

**Issue by prjemian** [BCDA-APS/bluesky_training#212]

**Comment by prjemian** [comment]
These are the steps I see now:

- [ ] Assign a MongoDB catalog ([BCDA instructions](https://git.aps.anl.gov/bcda/bluesky-catalogs/-/blob/master/README.md))
- [ ] [run `new_bluesky_instrument.py ~/bluesky`](https://bcda-aps.github.io/bluesky_training/instrument/_install_new_instrument.html)
- [ ] [create conda environment](https://bcda-aps.github.io/bluesky_training/reference/_create_conda_env.html)
- [ ] [databroker catalog configuration](https://bcda-aps.github.io/bluesky_training/instrument/_configure_databroker.html#setup-your-databroker-catalog-configuration)
- [ ] [configure bash with environment variable and alias](https://bcda-aps.github.io/bluesky_training/reference/_create_conda_env.html#create-an-alias-to-activate-the-bluesky-environment)
- [ ] create soft link:  `~/bin/blueskyStarter.sh`  -->  `~/bluesky/blueskyStarter.sh`
- [ ] [start a GitHub repository](https://bcda-aps.github.io/bluesky_training/reference/_github_create_repo.html)

**Comment by prjemian** [comment]
Revised this a couple times while installing 2iddnx and 2idenx.
